name: bipenc
description: "BiPenc - Sistema Experto de Inventario y POS. Desarrollado por Jhonatan (Ing. de Sistemas)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Gestión de Estado y Rutas (Responsabilidad Única)
  provider: ^6.1.2
  go_router: ^13.2.0

  # Cámara y Procesamiento de Imágenes (IA Local)
  camera: ^0.11.0
  path_provider: ^2.1.2
  google_mlkit_selfie_segmentation: ^0.5.0 # Para el recorte de fondo tipo AI

  # Impresión Térmica y Documentos
  print_bluetooth_thermal: ^1.2.0
  esc_pos_utils: ^1.1.0
  pdf: ^3.10.8

  # Persistencia y Nube
  supabase_flutter: ^2.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  logger: ^2.0.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_bipenc.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo_bipenc.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
